-- MySQL Script generated by MySQL Workbench
-- Tue May  8 12:09:37 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema valkiria_chatbot_mysql
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema valkiria_chatbot_mysql
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `valkiria_chatbot_mysql` DEFAULT CHARACTER SET utf8 ;
USE `valkiria_chatbot_mysql` ;

-- -----------------------------------------------------
-- Table `valkiria_chatbot_mysql`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `valkiria_chatbot_mysql`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre_usuario` VARCHAR(45) NOT NULL,
  `creado_en` DATETIME NULL,
  `actualizado_en` DATETIME NULL,
  `activo` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `valkiria_chatbot_mysql`.`conversacion_bot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `valkiria_chatbot_mysql`.`conversacion_bot` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuarios_id` INT NOT NULL,
  `_conversacion_id` VARCHAR(255) NOT NULL,
  `canal_socket` VARCHAR(255) NOT NULL,
  `fecha_creacion` DATETIME NULL,
  `fecha_actualizacion` VARCHAR(45) NULL,
  `texto` TEXT NOT NULL,
  PRIMARY KEY (`id`, `usuarios_id`),
  INDEX `fk_conversacion_usuarios3_idx` (`usuarios_id` ASC),
  CONSTRAINT `fk_conversacion_usuarios3`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `valkiria_chatbot_mysql`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
